version: '3'
services:
  devenv:
    image: engemil/ubuntu-embedded-dev-env:latest
    command: /bin/bash
    devices:
      - "/dev/bus/usb/"
    tty: true
    volumes:
      - ../..:/workspaces:cached # To be able to spin up from devcontainers
    #  - /dev/bus/usb:/dev/bus/usb # Using devices instead
