version: '3'
services:
  chibios_devcont:
    build:
      context: .
      dockerfile: Dockerfile # The path to our Dockerfile
    command: /bin/bash
    ports:
      - "3333:3333" # GDB Server Port
      - "4444:4444" # Telnet Server Port
      - "6666:6666" # TCL Server Port
    devices:
      - "/dev/bus/usb/:/dev/bus/usb"
    privileged: true
    tty: true
    volumes:
      - ..:/workspace:cached # To be able to spin up from devcontainers # Wierd build message: http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
    #  - /dev/bus/usb:/dev/bus/usb # Using devices instead
