# Use the latest Ubuntu image from Docker Hub
# NB! Ubuntu 22.04 is the latest compatible version for stm32cubeclt
FROM ubuntu:22.04

# update packages and install python
RUN apt-get update
RUN apt-get install usbutils -y

